steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/hangouts-chat-integration/docker-test:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/hangouts-chat-integration/docker-test:$SHORT_SHA']
